# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: strain_seq-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::numpy>=1.21
  - conda-forge::python>=3.7, <3.9
  - conda-forge::gawk>=5.1
  - conda-forge::pigz>=2.3               ## Required for TrimGalore multi-threading
  - conda-forge::textwrap3>=0.9
  - conda-forge::pandas>=1.4
  - conda-forge::r-base>=3.6
  - conda-forge::r-optparse>=1.7
  - conda-forge::r-rcolorbrewer>=1
  - conda-forge::r-reshape2>=1.4
  - conda-forge::r-ggplot2>=3.3
  - conda-forge::r-tidyr>=1.1
  - conda-forge::r-scales>=1.1
  - conda-forge::r-pheatmap>=1.0
  - conda-forge::r-matrixstats>=0.6
  - conda-forge::r-umap>=0.2

  ## bioconda packages
  - bioconda::fastqc>=0.11
  - bioconda::trim-galore>=0.1
  - bioconda::kallisto>=0.4
  - bioconda::bioconductor-edger>=3.3
  - bioconda::bioconductor-deseq2>=1.3
  - bioconda::pyfaidx>=0.6
